#!/usr/bin/env bash
set -u

prompt=""
IFS= read -r -d '' prompt || true
tools=""
session="fake-session-id"
resumed=false
bare=false
dangerous=false
dont_ask=false

while (($# > 0)); do
  case "$1" in
    --tools)
      tools="$2"
      shift 2
      ;;
    --sessions)
      session="$2"
      resumed=true
      shift 2
      ;;
    --permission-mode)
      [[ "$2" == "dontAsk" ]] && dont_ask=true
      shift 2
      ;;
    --bare)
      bare=true
      shift
      ;;
    --dangerously-skip-permissions)
      dangerous=true
      shift
      ;;
    *)
      shift
      ;;
  esac
done

if [[ "$prompt" == *"DELAY"* ]]; then sleep 2; fi
if [[ "$prompt" == *"CLI_FAILURE"* ]]; then
  echo "No conversation found" >&2
  exit 1
fi

if [[ ",$tools," == *",Write,"* ]]; then
  output_root="$PWD/outputs/knowledge"
  mkdir -p "$output_root"
  printf '# Generated by fake CodeAgent\n' > "$output_root/generated.md"
  printf '{"type":"user","tool_use_result":{"type":"create","filePath":"%s"}}\n' "$output_root/generated.md"
fi

printf '{"type":"result","subtype":"success","is_error":false,"result":"{\\"tools\\":\\"%s\\",\\"resumed\\":%s,\\"bare\\":%s,\\"dangerous\\":%s,\\"dontAsk\\":%s}","session_id":"%s","duration_ms":12,"num_turns":1,"usage":{"input_tokens":10,"output_tokens":5},"permission_denials":[]}\n' \
  "$tools" "$resumed" "$bare" "$dangerous" "$dont_ask" "$session"
